# Generated by Django 3.1.14 on 2022-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0004_sensorvaluetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErgAnalyse',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('raum_id', models.BigIntegerField()),
                ('periode', models.BigIntegerField()),
                ('periode_typ', models.BigIntegerField()),
                ('von_date_time', models.DateTimeField()),
                ('bis_date_time', models.DateTimeField()),
                ('wert_typ', models.BigIntegerField()),
                ('tgt_val', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('min_val', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('max_val', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('rise_time', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('max_rise', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('min_rise', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('goodness', models.BigIntegerField()),
                ('optimum_percent', models.BigIntegerField()),
                ('log_datum_vom', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='raumliste',
            name='groesse_qm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='raumliste',
            name='raumhoehe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='raumliste',
            name='wunsch_luftfeuchte',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='raumliste',
            name='wunsch_temperatur',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
