# Generated by Django 3.1.14 on 2022-06-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0005_auto_20220526_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erganalyse',
            name='bis_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='erganalyse',
            name='von_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
