# Generated by Django 4.0.4 on 2022-05-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ki_energie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KiParams',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('subgroup', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('val_int', models.IntegerField(blank=True, null=True)),
                ('val_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('val_string', models.CharField(blank=True, max_length=45, null=True)),
                ('log_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ki_params',
                'managed': False,
            },
        ),
    ]
