# Generated by Django 4.0.4 on 2022-05-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ki_energie', '0002_kiparams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adressen',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='auwstatkurven',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='geraete',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='geraete2kunde',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='importboxfehlerlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='importmesswerte',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kiparams',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kirgactor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kirgactorsensor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kirgdata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kirggewerk',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kirgsensor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kirgtypen',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kunde',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='raumliste',
            options={'managed': True},
        ),
    ]
