CREATE TABLE IF NOT EXISTS `kunde` (  
    `kunde_Id` int NOT NULL AUTO_INCREMENT,
    `anrede` VARCHAR(5) DEFAULT NULL,
    `titel` VARCHAR(20) DEFAULT NULL,
    `vorname` VARCHAR(60) DEFAULT NULL,
    `nachname` VARCHAR(60) DEFAULT NULL,
    `plz` VARCHAR(5) DEFAULT NULL,
    `ort` VARCHAR(50) DEFAULT NULL,
    `strasse` VARCHAR(50) DEFAULT NULL,
    `hausnummer` VARCHAR(6) DEFAULT NULL,
    `festnetz` VARCHAR(60) DEFAULT NULL,
    `faxnummer` VARCHAR(60) DEFAULT NULL,
    `mobil` VARCHAR(60) DEFAULT NULL,
    `mail` VARCHAR(128) DEFAULT NULL,
    `anmeldename` VARCHAR(20) DEFAULT NULL,
    `passwort` VARCHAR(60) DEFAULT NULL,
    `anmeldung_aktiv` BIT DEFAULT NULL,
    `bemerkung` VARCHAR(100) DEFAULT NULL,
    `log_erzeugt_am` datetime DEFAULT CURRENT_TIMESTAMP,
    `log_letzte_änderung_am` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`kunde_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3