# Generated by Django 4.0.4 on 2022-05-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0001_initial'),
    ]

