# Generated by Django 4.0.4 on 2022-05-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geraete2',
        ),
        migrations.AlterField(
            model_name='kirgsensor',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
