# Generated by Django 3.1.14 on 2022-05-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0002_delete_geraete2_alter_kirgsensor_name'),
    ]
