# Generated by Django 3.2.14 on 2022-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0008_auto_20220806_0800'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP VIEW IF EXISTS ki_energie_RaumlisteInd1;
            CREATE OR REPLACE VIEW ki_energie_RaumlisteInd1 AS SELECT DISTINCT server_name, etage, raum FROM decarbonara.ki_energie_Raumliste order by server_name, etage, raum;
    """
        )
    ]
