# Generated by Django 3.2.14 on 2022-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0009_auto_20220819_1510'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP Table IF EXISTS ki_energie_adressen;
        """    
        ),
        
        migrations.CreateModel(
            name='Adressen',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True)),
                ('strasse', models.CharField(blank=True, max_length=200, null=True)),
                ('hausnummer', models.CharField(blank=True, max_length=10, null=True)),
                ('postleitzahl', models.CharField(blank=True, max_length=10, null=True)),
                ('iso_land', models.CharField(blank=True, max_length=5, null=True)),
                ('land', models.CharField(blank=True, max_length=200, null=True)),
                ('ort', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('festnetz', models.CharField(blank=True, max_length=60, null=True)),
                ('faxnummer', models.CharField(blank=True, max_length=60, null=True)),
                ('mobil', models.CharField(blank=True, max_length=60, null=True)),
                ('mail', models.CharField(blank=True, max_length=128, null=True)),
                ('log_datum_vom', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        
        migrations.RunSQL("""
            DROP Table IF EXISTS ki_energie_dokumente;
        """    
        ),
        migrations.CreateModel(
            name='Dokumente',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('dok_typ', models.CharField(blank=True, max_length=20, null=True)),
                ('dok_id', models.BigIntegerField(blank=True, null=True)),
                ('dok_lfd', models.BigIntegerField(blank=True, null=True)),
                ('pfad', models.CharField(max_length=500)),
                ('name', models.TextField(max_length=128)),
                ('log_datum_vom', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        
        migrations.RunSQL("""
            DROP Table IF EXISTS ki_energie_etage;
        """    
        ),
        migrations.CreateModel(
            name='Etage',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gebaeude_id', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('log_datum_vom', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        
        migrations.RunSQL("""
            DROP Table IF EXISTS ki_energie_gebaeude;
        """    
        ),
        migrations.CreateModel(
            name='Gebaeude',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('adress_id', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('log_datum_vom', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        
        migrations.RunSQL("""
            DROP Table IF EXISTS ki_energie_Kommentar;
        """    
        ),
        
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('ext_typ', models.CharField(blank=True, max_length=20, null=True)),
                ('ext_id', models.BigIntegerField(blank=True, null=True)),
                ('ext_lfd', models.BigIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('log_datum_vom', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        
        migrations.RunSQL("""
            DROP Table IF EXISTS ki_energie_RaumlisteInd1;
        """    
        ),
        migrations.CreateModel(
            name='RaumlisteInd1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(blank=True, max_length=20, null=True)),
                ('etage', models.CharField(blank=True, max_length=50, null=True)),
                ('raum', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        
        migrations.RunSQL("""
            DROP Table IF EXISTS ki_energie_server;
        """    
        ),
        
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('kunde_id', models.BigIntegerField(blank=True, null=True)),
                ('gebaeude_id', models.BigIntegerField(blank=True, null=True)),
                ('etage_id', models.BigIntegerField(blank=True, null=True)),
                ('raum_id', models.BigIntegerField(blank=True, null=True)),
                ('montageort', models.CharField(blank=True, max_length=200, null=True)),
                ('serial_nbr', models.CharField(blank=True, max_length=50, null=True)),
                ('hw_version', models.CharField(blank=True, max_length=200, null=True)),
                ('os_system', models.CharField(blank=True, max_length=200, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('log_datum_vom', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        
        migrations.RunSQL("""
            DROP Table IF EXISTS ki_energie_status;
        """    
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('ext_typ', models.CharField(blank=True, max_length=20, null=True)),
                ('ext_id', models.BigIntegerField(blank=True, null=True)),
                ('ext_lfd', models.BigIntegerField(blank=True, null=True)),
                ('stat_typ', models.CharField(blank=True, max_length=5, null=True)),
                ('stat_text', models.TextField(blank=True, null=True)),
                ('log_datum_vom', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        
        migrations.RunSQL("""
            DROP Table IF EXISTS ki_energie_kunde;
        """    
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('anrede', models.CharField(blank=True, max_length=5, null=True)),
                ('titel', models.CharField(blank=True, max_length=20, null=True)),
                ('vorname', models.CharField(blank=True, max_length=60, null=True)),
                ('nachname', models.CharField(blank=True, max_length=60, null=True)),
                ('plz', models.CharField(blank=True, max_length=5, null=True)),
                ('ort', models.CharField(blank=True, max_length=50, null=True)),
                ('strasse', models.CharField(blank=True, max_length=50, null=True)),
                ('hausnummer', models.CharField(blank=True, max_length=6, null=True)),
                ('festnetz', models.CharField(blank=True, max_length=60, null=True)),
                ('faxnummer', models.CharField(blank=True, max_length=60, null=True)),
                ('mobil', models.CharField(blank=True, max_length=60, null=True)),
                ('mail', models.CharField(blank=True, max_length=128, null=True)),
                ('anmeldename', models.CharField(blank=True, max_length=20, null=True)),
                ('passwort', models.CharField(blank=True, max_length=60, null=True)),
                ('anmeldung_aktiv', models.TextField(blank=True, null=True)),
                ('bemerkung', models.CharField(blank=True, max_length=100, null=True)),
                ('log_erzeugt_am', models.DateTimeField(blank=True, null=True)),
                ('log_letzte_änderung_am', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        
        migrations.AlterModelOptions(
            name='kunde',
            options={'ordering': ['nachname', 'vorname']},
        ),
        migrations.AlterModelOptions(
            name='sensorvaluetypes',
            options={'ordering': ['sub_kategorie', 'sub_kategorie_name']},
        ),
        migrations.AlterModelOptions(
            name='workparameter',
            options={'ordering': ['app', 'modul', 'name', 'subname']},
        ),
        migrations.RenameField(
            model_name='kunde',
            old_name='log_erzeugt_am',
            new_name='kunde_anlage',
        ),
        migrations.RenameField(
            model_name='kunde',
            old_name='log_letzte_änderung_am',
            new_name='log_datum_vom',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='bemerkung',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='faxnummer',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='festnetz',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='hausnummer',
        ),
        
        migrations.RemoveField(
            model_name='kunde',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='mobil',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='strasse',
        ),
        
        
        
    ]
