# Generated by Django 3.2.14 on 2022-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0010_auto_20220823_1619'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='erganalyse',
            name='etage_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erganalyse',
            name='gebaeude_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erganalyse',
            name='geraete_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='erganalyse',
            name='kunde_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erganalyse',
            name='server_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        
    ]
