# Generated by Django 3.2.14 on 2022-09-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0011_auto_20220829_1621'),
    ]

    operations = [
        
        
        migrations.AddField(
            model_name='kunde',
            name='adress_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kunde',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kunde',
            name='comments_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        
    ]
