# Generated by Django 3.2.14 on 2022-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0015_auto_20220911_1356'),
    ]

    operations = [

        migrations.AlterField(
            model_name='raumliste',
            name='server_id',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
    ]
