# Generated by Django 3.2.14 on 2022-09-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0016_auto_20220911_1359'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='Raumliste',
            name='kunde_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
