# Generated by Django 3.2.14 on 2022-09-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0018_auto_20220911_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geraete',
            old_name='log_erzeugt_am',
            new_name='log_datum_vom',
        ),
        migrations.RenameField(
            model_name='sensorvaluetypes',
            old_name='log_erzeugt_am',
            new_name='log_datum_vom',
        ),
        migrations.RemoveField(
            model_name='geraete',
            name='bemerkung',
        ),
        migrations.RemoveField(
            model_name='geraete',
            name='log_letzte_aenderung_am',
        ),
        
        migrations.RemoveField(
            model_name='sensorvaluetypes',
            name='log_letzte_aenderung_am',
        ),
        migrations.AddField(
            model_name='geraete',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
