# Generated by Django 3.2.14 on 2022-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0019_auto_20220913_0909'),
    ]

    
