# Generated by Django 3.2.14 on 2022-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0020_auto_20220913_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geraete',
            name='geraete_id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
    ]
