# Generated by Django 3.2.14 on 2023-03-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0021_alter_geraete_geraete_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='mst_messtelle',
            fields=[
                ('id', models.AutoField(db_column='id',
                 primary_key=True, serialize=False)),
                ('zaehler_nr', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('zaehler_typ', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('zaehler_einheit', models.BigIntegerField(blank=True, null=True)),
                ('zaehler_name', models.TextField(max_length=128)),
                ('log_datum_erfasst', models.DateTimeField(blank=True, null=True)),
                ('log_datum_ltz_aend', models.DateTimeField(blank=True, null=True)),
                ('log_user', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        
    ]
